import asyncio
from playwright import async_api
from playwright.async_api import expect

async def run_test():
    pw = None
    browser = None
    context = None
    
    try:
        # Start a Playwright session in asynchronous mode
        pw = await async_api.async_playwright().start()
        
        # Launch a Chromium browser in headless mode with custom arguments
        browser = await pw.chromium.launch(
            headless=True,
            args=[
                "--window-size=1280,720",         # Set the browser window size
                "--disable-dev-shm-usage",        # Avoid using /dev/shm which can cause issues in containers
                "--ipc=host",                     # Use host-level IPC for better stability
                "--single-process"                # Run the browser in a single process mode
            ],
        )
        
        # Create a new browser context (like an incognito window)
        context = await browser.new_context()
        context.set_default_timeout(5000)
        
        # Open a new page in the browser context
        page = await context.new_page()
        
        # Navigate to your target URL and wait until the network request is committed
        await page.goto("http://localhost:5001", wait_until="commit", timeout=10000)
        
        # Wait for the main page to reach DOMContentLoaded state (optional for stability)
        try:
            await page.wait_for_load_state("domcontentloaded", timeout=3000)
        except async_api.Error:
            pass
        
        # Iterate through all iframes and wait for them to load as well
        for frame in page.frames:
            try:
                await frame.wait_for_load_state("domcontentloaded", timeout=3000)
            except async_api.Error:
                pass
        
        # Interact with the page elements to simulate user flow
        # --> Assertions to verify final state
        frame = context.pages[-1]
        await expect(frame.locator('text=Welcome to AI-AAC! 💬').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=About This App').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=This is a demo of an AI-assisted AAC software designed to be an assistive technology for nonverbal communicators.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=The Problem: Currently, AAC softwares provide ~50 words at a time, unchanging by context and are woefully inadequate for communication. There are hundreds of reasons a person may be nonverbal, and almost none of them involve an impairment in language comprehension.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=The Solution: Context-dependent suggestions make picking words easier, and the "generate sentences" button lets you choose from nuanced variations of what you want to say. You can also send a photo to generate ~100 context-relevant vocabulary words for your current situation!').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=The Team: Built by Sam Lederer (Computational Linguistics), Elizabeth Weber (Bioengineering), and Meeta Pandit (Data Engineering). This was a truly interdisciplinary project that couldn\'t have been explored without all three of our very different skill sets. We enjoyed connecting with everyone at the hackathon and are open to new opportunities. Feel free to reach out!').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💡 Interested in this project? Elizabeth Weber is actively leading the continued development of this assistive technology. To collaborate or learn more, contact her at lizweber2021@gmail.com').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=To get started, please select a voice for text-to-speech.').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔊 Select Voice:').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Loading voices...').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔊 Test Voice').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Continue').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Word Bank').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📷 Add Context').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔊').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=→').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤖').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Context (0)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👤 Pronouns (27)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👤 I').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👥 you').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👨 he').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👩 she').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⚡ it').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👫 we').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👥 they').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙋 me').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙋‍♂️ him').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙋‍♀️ her').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤝 us').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👬 them').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📌 my').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📍 your').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔹 his').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔸 her').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⭐ its').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌟 our').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✨ their').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👉 this').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👈 that').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔽 these').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔼 those').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❓ who').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❔ what').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔀 which').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏷️ whose').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❓').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Question Words (13)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❓ who').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❔ what').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰ when').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📍 where').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤔 why').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🛠️ how').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔀 which').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏷️ whose').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💰 how much').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔢 how many').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏱️ how long').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📏 how far').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔁 how often').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Prepositions (41)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📥 in').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔛 on').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📍 at').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👉 by').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤝 with').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬅️ from').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=➡️ to').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📦 of').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🎁 for').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💭 about').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬆️ above').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶️ after').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚫 against').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🛤️ along').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🎪 among').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔄 around').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏪ before').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬇️ behind').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔽 below').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬌ between').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌌 beyond').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬇️ down').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏳ during').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚷 except').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏠 inside').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📥 into').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💝 like').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📌 near').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔌 off').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚪 out').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏞️ outside').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔝 over').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏮️ past').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📅 since').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔀 through').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🎯 toward').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬇️ under').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏳ until').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬆️ up').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📦 within').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚫 without').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙏').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Politeness (6)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙏 please').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💝 thank you').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙌 thanks').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=😔 sorry').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙋 excuse me').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤗 welcome').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👋').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Greetings (13)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👋 hello').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✋ hi').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🙌 hey').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌅 good morning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=☀️ good afternoon').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌆 good evening').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌙 good night').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👋 goodbye').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✌️ bye').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👀 see you').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💝 take care').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤝 nice to meet you').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❓ how are you').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🗺️').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Location (24)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📍 here').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👉 there').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌍 everywhere').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❓ somewhere').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🗺️ anywhere').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚫 nowhere').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬆️ up').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬇️ down').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬅️ left').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=➡️ right').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶️ forward').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=◀️ backward').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔜 ahead').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔙 behind').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📌 nearby').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌌 far').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤏 close').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=↗️ away').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔄 around').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏠 inside').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌳 outside').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬆️ upstairs').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬇️ downstairs').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=↔️ next to').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Time (28)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⚡ now').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰ then').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📅 today').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏮️ yesterday').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏭️ tomorrow').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌙 tonight').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌅 morning').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=☀️ afternoon').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌆 evening').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌃 night').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰ later').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔜 soon').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰ early').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⌛ late').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏪ before').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏩ after').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏳ during').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⌚ while').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=♾️ always').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚫 never').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔄 sometimes').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📊 often').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🥉 rarely').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📈 usually').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✅ already').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰ yet').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏸️ still').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⚡ just').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👁️').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Senses (9)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👁️ see').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👀 look').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📺 watch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👂 hear').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🎧 listen').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👃 smell').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👅 taste').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤚 touch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💭 feel').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=Thinking & Feeling (50)').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🧠 know').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💭 think').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✨ believe').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💡 understand').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🧠 remember').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌫️ forget').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📚 learn').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌈 imagine').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💝 want').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📍 need').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❤️ like').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💖 love').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💔 hate').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💝 care').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⚡ do').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔨 make').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📦 get').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤲 take').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🎁 give').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📌 put').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔧 use').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔍 find').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👉 show').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤝 help').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✅ let').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📦 keep').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👋 leave').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶️ start').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏹️ stop').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏁 end').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=▶️ continue').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💪 try').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❌ fail').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💼 work').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🎮 play').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=😴 rest').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰ wait').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📍 stay').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔄 become').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔀 change').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🌱 grow').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=➕ add').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=➖ remove').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📉 lose').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏆 win').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🛒 buy').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💵 sell').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💸 spend').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💰 save').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤝 share').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚶 go').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👋 come').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏃 move').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚶 walk').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏃 run').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🦘 jump').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🧗 climb').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬇️ fall').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🪑 sit').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🧍 stand').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=😴 sleep').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⏰ wake').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔄 turn').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👉 push').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤲 pull').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬆️ lift').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📦 carry').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤲 hold').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✊ grab').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤾 catch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🎯 throw').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👊 hit').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🦵 kick').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤚 touch').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤲 reach').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👉 point').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👋 wave').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚪 open').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔒 close').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💥 break').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🔧 fix').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🏗️ build').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=✨ clean').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🚿 wash').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💨 dry').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=👕 wear').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=➖ remove').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=⬇️ drop').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💬 say').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🗣️ tell').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💬 talk').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=❓ ask').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=💡 answer').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=↩️ reply').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📖 explain').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📝 describe').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📞 call').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=📣 shout').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🤫 whisper').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=😱 yell').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=😂 laugh').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=😊 smile').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🍽️ eat').first).to_be_visible(timeout=30000)
        await expect(frame.locator('text=🥤 drink').first).to_be_visible(timeout=30000)
        await asyncio.sleep(5)
    
    finally:
        if context:
            await context.close()
        if browser:
            await browser.close()
        if pw:
            await pw.stop()
            
asyncio.run(run_test())
    